<#-- @ftlvariable name="import" type="com.dell.dims.Model.bpel.Import" -->
<#-- @ftlvariable name="component" type="soa.model.Component" -->
<#-- @ftlvariable name="wire" type="soa.model.wire" -->
<?xml version="1.0" encoding="UTF-8" ?>
<!-- Generated by Oracle SOA Modeler version 12.1.3.0.0 at [11/20/17 12:27 PM]. -->
<composite name="${compositeFileName}"
           revision="1.0"
           label="2017-11-20_12-27-28_723"
           mode="active"
           state="on"
           xmlns="http://xmlns.oracle.com/sca/1.0"
           xmlns:xs="http://www.w3.org/2001/XMLSchema"
           xmlns:wsp="http://schemas.xmlsoap.org/ws/2004/09/policy"
           xmlns:orawsp="http://schemas.oracle.com/ws/2006/01/policy"
           xmlns:ui="http://xmlns.oracle.com/soa/designer/"
           xmlns:sca-ext="http://xmlns.oracle.com/sca/1.0-ext">

       <#list imports as import>
           <import namespace="${import.namespace}"
                        location="${import.location}" importType="wsdl"/>
       </#list>

   <#list components as component>

     <service name="${component.componentType.service.name}_ep" ui:wsdlLocation="${component.componentType.service.wsdlLocation}">
          <interface.wsdl interface="${component.componentType.service.interfaceWsdl}"/>
           <binding.ws port="${component.componentType.service.bindingPort}"/>

     </service>

    </#list>

   <property name="productVersion" type="xs:string" many="false">12.1.3.0.0</property>
   <property name="compositeID" type="xs:string" many="false">${compositeId}</property>

<#list components as component>
        <component name="${component.name}" version="2.0">
             <implementation.bpel src="${component.implementationBpel}"/>
                <componentType>
                     <service name="${component.componentType.service.name}" ui:wsdlLocation="${component.componentType.service.wsdlLocation}">
                            <interface.wsdl interface="${component.componentType.service.interfaceWsdl}"/>
                     </service>
                      <reference name="${component.componentType.reference.name}"
                           ui:wsdlLocation="${component.componentType.reference.uiWsdlLocation}">
                        <interface.wsdl interface="${component.componentType.reference.interfaceWsdl}"/>
                      </reference>
                </componentType>
        </component>
    </#list>

<#list wires as wire>
 <wire>
    <source.uri>${wire.source}</source.uri>
    <target.uri>${wire.target}</target.uri>
  </wire>
</#list>

 </composite>
